name: FlappyRust
options:
  bundleIdPrefix: com.matthieud134
targets:
  FlappyRust:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    info:
      path: Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchScreen: {}
    sources:
      - path: ../assets
        name: assets
        type: folder
      - path: Assets.xcassets
      - path: dummy.c
        name: dummy.c
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      PRODUCT_BUNDLE_IDENTIFIER: com.matthieud134.flappy-rust
      ENABLE_BITCODE: NO
      OTHER_LDFLAGS:
        - $(inherited)
        - -L${PROJECT_DIR}/../target/aarch64-apple-ios/debug
        - -L${PROJECT_DIR}/../target/aarch64-apple-ios-sim/debug
        - -lflappy_rust
        - -framework AVFoundation
        - -framework AudioToolbox
        - -framework CoreGraphics
        - -framework CoreMedia
        - -framework CoreVideo
        - -framework QuartzCore
        - -framework UIKit
        - -framework Metal
        - -framework GameController
    preBuildScripts:
      - name: Build Rust Library
        basedOnDependencyAnalysis: false
        script: |
          set -e  # Fail on error
          echo "🚀 Starting Rust Build Phase..."
          
          # Add Cargo to PATH
          export PATH="$HOME/.cargo/bin:$PATH"
          
          # Go to project root
          cd ..
          
          echo "📂 Working directory: $(pwd)"
          echo "📱 Platform: $PLATFORM_NAME"
          
          if [ "$PLATFORM_NAME" = "iphonesimulator" ]; then
              echo "🛠 Building for iOS Simulator..."
              cargo build --target aarch64-apple-ios-sim --verbose
          else
              echo "🛠 Building for iOS Device..."
              cargo build --target aarch64-apple-ios --verbose
          fi
          
          echo "✅ Rust Build Complete!"
